version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticketmaster-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ticketmaster?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=ticketmaster
      - SPRING_DATASOURCE_PASSWORD=ticketmaster
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - ticketmaster-network
    restart: always

  mysql:
    image: mysql:8.0
    container_name: ticketmaster-mysql
    environment:
      - MYSQL_DATABASE=ticketmaster
      - MYSQL_USER=ticketmaster
      - MYSQL_PASSWORD=ticketmaster
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - ticketmaster-network
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks:
  ticketmaster-network:
    driver: bridge

volumes:
  mysql-data: